[functions.payu-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/payu-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/payu-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/payu-webhook/*.html" ]

[functions.create-payu-button]
verify_jwt = false

# Email template configuration

[auth.email.template.confirmation]
subject = "Confirm your PrescriptionAI Saathi registration"
content_path = "templates/confirmation.html"
